### ISSUE TITLE
Add ability to find latest applicable mapnik version

### ISSUE THREAD

**Issue by flippmoke** [mapnik/mapnik-reference#108]
Currently it is required that every single version of Mapnik have its own folder in mapnik reference, however, with the quicker iteration of mapnik releases there may not always be any changes to mapnik-reference required. Therefore mapnik-reference should attempt to auto detect a version if the folder does not exist.

The auto finding of another version of mapnik should only find *the latest patch version that is lower then or equal to the version of mapnik*. 

Therefore:

If our versions in mapnik-reference are:

* 3.0.0
* 3.0.3

`3.0.1` would use `3.0.0`
`3.0.3` would use `3.0.3`
`3.0.4` would use `3.0.3`
`3.1.0` would fail because there is not a `3.1.0`

/cc @yohanboniface

**Comment by yohanboniface** [comment]
One question: are we sure we want to have versions for patches? A patch means that the API has not changed, and thus, given that the mapnik-reference describes the API, I'm not sure it makes sense to have versions for Mapnik patches here. Thoughts?

**Comment by flippmoke** [comment]
@yohanboniface It is possible that a patch release could introduce new features but not disrupt any existing API features, so yes.

**Comment by yohanboniface** [comment]
Okay. It feel we could find a simpler workflow, but let's go this way for now. :)
@flippmoke can you set `gh-pages` as default branch? cf #107

**Comment by springmeyer** [comment]
landed in 08437ab
