### ISSUE TITLE
The site should link to this repository

### ISSUE THREAD

**Issue by talaj** [mapnik/mapnik-reference#123]
The http://mapnik.org/mapnik-reference/ should contain information that it's generated from this repository and encourage contribution if something wrong or incomplete.

**Comment by springmeyer** [comment]
Good idea @talaj. Feel free to PR over at https://github.com/mapnik/mapnik.github.com. Also backstory on @yohanboniface's work to get this in place at https://github.com/mapnik/mapnik.github.com/issues/25
