### ISSUE TITLE
Failure at postinstall node generate.js

### ISSUE THREAD

**Issue by nebulon42** [mapnik/mapnik-reference#133]
I have seen this in Travis and it seems also to affect users.
Ref https://github.com/mapbox/carto/issues/468.

I'm not sure what causes this.

**Comment by springmeyer** [comment]
Maybe we could do the generation at publish time with the `prepublish` hook? Or just have a build step that we run as developers and check the modified file into git...

**Comment by nebulon42** [comment]
Yes, that's we we are doing. But additionally we had to add the postinstall target because of https://github.com/mapnik/mapnik-reference/commit/394e2396f4b50d8d64a4b3c7c7d4f5d1f150e929#commitcomment-20397440. Maybe we could instead change mapnik-swoop accordingly?

**Comment by nebulon42** [comment]
The postinstall script fails if `node` does not run the node binary as it is the case on systems where it is named `nodejs` (e.g. Ubuntu via apt). The only solutions I see is either not being able to install via git and keeping `prepublish` or adding the generated `index.js` to version control. The first option is less error prone in my opinion.

**Comment by nebulon42** [comment]
Workaround for Ubuntu: install the package `nodejs-legacy` to make sure that the Node.js binary is also accessible via `node`.
