### ISSUE TITLE
text-upright is missing in 3.0.0

### ISSUE THREAD

**Issue by talaj** [mapnik/mapnik-reference#81]
The upright property of TextSymbolizer is missing in the reference for 3.0.0.

**Comment by springmeyer** [comment]
thanks @mojodna for catching this, yet all done here after #92.

**Comment by mojodna** [comment]
_checks it off his TODO list_  (I'd been meaning to do this, but it never got sufficiently pressing.)

**Comment by springmeyer** [comment]
Woot. Hey, also aiming to be at Cugos next week - hope to see you there.

**Comment by mojodna** [comment]
Will do, just needed a little nudge!
